#SERVICE INFO
info:
  app:
    name: Stoom-Products-API
    description: Coding Challange
    version: 0.0.1
  java:
    vendor: ${java.specification.vendor}
    version: ${java.version}
  od:
    arch: ${os.arch}
    name: ${os.name}
    version: ${os.version}

#ACTUATOR
management:
  endpoints:
    web:
      base-path: /management
      exposure: { include: [info, health, metrics, http-trace, env, mappings, sessions, config-props, beans ]}
  endpoint:
    info:
      enabled: true
      show-details: always
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
      show-details: always
    http-trace:
      enabled: true
    env:
      enabled: true
    mappings:
      enabled: true
    sessions:
      enabled: true
    config-props:
      enabled: true
    beans:
      enabled: true


spring:
  datasource:
    driverClassName: org.h2.Driver
    username: stoom
    password:
    url: jdbc:h2:mem:productdb
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

  main:
    banner-mode: off